employee_file = open("/Volumes/Data/Documents/scpark/VSC/workspace/python/.vscode/employees.txt", "a")
# employee_file.write("Toby - Human Resources\n")
employee_file.write("Kelly - Customer Service\n")
# print(employee_file.read())
employee_file.close()